apiVersion: v1
kind: Pod
metadata:
  name: devopsmicroservices-pod
spec:
  containers:
  - name: private-reg-container
    image: 491808826414.dkr.ecr.us-east-1.amazonaws.com/devopsmicroservices:latest
  imagePullSecrets:
  - name: regcred